const KEY_PATTERN = 'MMMM Do YYYY, h:mm:ss';
const CRON_EVERY_SECOND = '* * * * * *';
const TIMEZONE = 'America/Los_Angeles';
const SERVER_NOT_AVAILABLE_KEY = 'SERVER_NOT_AVAILABLE_KEY';

module.exports = {
	KEY_PATTERN,
	CRON_EVERY_SECOND,
	TIMEZONE,
	SERVER_NOT_AVAILABLE_KEY,
}
