const KEY_PATTERN = 'MMMM Do YYYY, h:mm:ss';
const CRON_EVERY_SECOND = '* * * * * *';
const TIMEZONE = 'America/Los_Angeles';
const SERVER_NOT_AVAILABLE_KEY = 'SERVER_NOT_AVAILABLE_KEY';

const HTTP_STATUS_CODE = {
	ACCEPTED: 202,
	FAILURE: 400,
}

module.exports = {
	KEY_PATTERN,
	CRON_EVERY_SECOND,
	TIMEZONE,
	SERVER_NOT_AVAILABLE_KEY,
	HTTP_STATUS_CODE,
}
